// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kywzojxckxsuaamuqcna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5d3pvanhja3hzdWFhbXVxY25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjgxNTYsImV4cCI6MjA1NDY0NDE1Nn0.rFF31NQ2H1gKVqpts1FaN-QpRZHfiwqehCOZbfRbMDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);